/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopPicksRouteImport } from './routes/top-picks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password.index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as VerifyCaptureRouteImport } from './routes/verify/capture'
import { Route as SignupVerifyRouteImport } from './routes/signup.verify'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsDiscoveryRouteImport } from './routes/settings/discovery'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ProfileMediaRouteImport } from './routes/profile/media'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password.verify'
import { Route as ForgotPasswordResetRouteImport } from './routes/forgot-password.reset'
import { Route as EventsJoinRouteImport } from './routes/events/join'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsManageEventIdRouteImport } from './routes/events/manage.$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TopPicksRoute = TopPicksRouteImport.update({
  id: '/top-picks',
  path: '/top-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCaptureRoute = VerifyCaptureRouteImport.update({
  id: '/verify/capture',
  path: '/verify/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignupRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDiscoveryRoute = SettingsDiscoveryRouteImport.update({
  id: '/settings/discovery',
  path: '/settings/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMediaRoute = ProfileMediaRouteImport.update({
  id: '/profile/media',
  path: '/profile/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/forgot-password/verify',
  path: '/forgot-password/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordResetRoute = ForgotPasswordResetRouteImport.update({
  id: '/forgot-password/reset',
  path: '/forgot-password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsJoinRoute = EventsJoinRouteImport.update({
  id: '/events/join',
  path: '/events/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsManageEventIdRoute = EventsManageEventIdRouteImport.update({
  id: '/events/manage/$eventId',
  path: '/events/manage/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/likes': typeof LikesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRouteWithChildren
  '/top-picks': typeof TopPicksRoute
  '/events/create': typeof EventsCreateRoute
  '/events/join': typeof EventsJoinRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/media': typeof ProfileMediaRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/discovery': typeof SettingsDiscoveryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/verify/capture': typeof VerifyCaptureRoute
  '/events/': typeof EventsIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/manage/$eventId': typeof EventsManageEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/likes': typeof LikesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/safety': typeof SafetyRoute
  '/top-picks': typeof TopPicksRoute
  '/events/create': typeof EventsCreateRoute
  '/events/join': typeof EventsJoinRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/media': typeof ProfileMediaRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/discovery': typeof SettingsDiscoveryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/verify/capture': typeof VerifyCaptureRoute
  '/events': typeof EventsIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/manage/$eventId': typeof EventsManageEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/likes': typeof LikesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRouteWithChildren
  '/top-picks': typeof TopPicksRoute
  '/events/create': typeof EventsCreateRoute
  '/events/join': typeof EventsJoinRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/media': typeof ProfileMediaRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/discovery': typeof SettingsDiscoveryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/verify/capture': typeof VerifyCaptureRoute
  '/events/': typeof EventsIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/manage/$eventId': typeof EventsManageEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/discover'
    | '/explore'
    | '/likes'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/safety'
    | '/signup'
    | '/top-picks'
    | '/events/create'
    | '/events/join'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/matches/$matchId'
    | '/profile/edit'
    | '/profile/media'
    | '/settings/account'
    | '/settings/discovery'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/signup/verify'
    | '/verify/capture'
    | '/events/'
    | '/forgot-password/'
    | '/matches/'
    | '/profile/'
    | '/settings/'
    | '/signup/'
    | '/verify/'
    | '/api/auth/$'
    | '/events/manage/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/discover'
    | '/explore'
    | '/likes'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/safety'
    | '/top-picks'
    | '/events/create'
    | '/events/join'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/matches/$matchId'
    | '/profile/edit'
    | '/profile/media'
    | '/settings/account'
    | '/settings/discovery'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/signup/verify'
    | '/verify/capture'
    | '/events'
    | '/forgot-password'
    | '/matches'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/verify'
    | '/api/auth/$'
    | '/events/manage/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/discover'
    | '/explore'
    | '/likes'
    | '/login'
    | '/onboarding'
    | '/premium'
    | '/safety'
    | '/signup'
    | '/top-picks'
    | '/events/create'
    | '/events/join'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/matches/$matchId'
    | '/profile/edit'
    | '/profile/media'
    | '/settings/account'
    | '/settings/discovery'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/signup/verify'
    | '/verify/capture'
    | '/events/'
    | '/forgot-password/'
    | '/matches/'
    | '/profile/'
    | '/settings/'
    | '/signup/'
    | '/verify/'
    | '/api/auth/$'
    | '/events/manage/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  LikesRoute: typeof LikesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRouteWithChildren
  TopPicksRoute: typeof TopPicksRoute
  EventsCreateRoute: typeof EventsCreateRoute
  EventsJoinRoute: typeof EventsJoinRoute
  ForgotPasswordResetRoute: typeof ForgotPasswordResetRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileMediaRoute: typeof ProfileMediaRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsDiscoveryRoute: typeof SettingsDiscoveryRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  VerifyCaptureRoute: typeof VerifyCaptureRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventsManageEventIdRoute: typeof EventsManageEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-picks': {
      id: '/top-picks'
      path: '/top-picks'
      fullPath: '/top-picks'
      preLoaderRoute: typeof TopPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/capture': {
      id: '/verify/capture'
      path: '/verify/capture'
      fullPath: '/verify/capture'
      preLoaderRoute: typeof VerifyCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/verify': {
      id: '/signup/verify'
      path: '/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof SignupRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/discovery': {
      id: '/settings/discovery'
      path: '/settings/discovery'
      fullPath: '/settings/discovery'
      preLoaderRoute: typeof SettingsDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/media': {
      id: '/profile/media'
      path: '/profile/media'
      fullPath: '/profile/media'
      preLoaderRoute: typeof ProfileMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/forgot-password/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/reset': {
      id: '/forgot-password/reset'
      path: '/forgot-password/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof ForgotPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/join': {
      id: '/events/join'
      path: '/events/join'
      fullPath: '/events/join'
      preLoaderRoute: typeof EventsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/manage/$eventId': {
      id: '/events/manage/$eventId'
      path: '/events/manage/$eventId'
      fullPath: '/events/manage/$eventId'
      preLoaderRoute: typeof EventsManageEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupVerifyRoute: typeof SignupVerifyRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupVerifyRoute: SignupVerifyRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  LikesRoute: LikesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRouteWithChildren,
  TopPicksRoute: TopPicksRoute,
  EventsCreateRoute: EventsCreateRoute,
  EventsJoinRoute: EventsJoinRoute,
  ForgotPasswordResetRoute: ForgotPasswordResetRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileMediaRoute: ProfileMediaRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsDiscoveryRoute: SettingsDiscoveryRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  VerifyCaptureRoute: VerifyCaptureRoute,
  EventsIndexRoute: EventsIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventsManageEventIdRoute: EventsManageEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
